# Generated by Django 5.0.6 on 2024-07-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_alter_contact_1_table_alter_contact_2_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_1',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contact_2',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contact_3',
            table=None,
        ),
    ]
