# Generated by Django 5.0.6 on 2024-07-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_contact_1_table_alter_contact_2_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_2',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
