# Generated by Django 5.0.6 on 2024-07-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_contact_2_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_3',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
