# Generated by Django 5.0.6 on 2024-07-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_alter_contact_3_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_3',
        ),
    ]
