# Generated by Django 5.0.6 on 2024-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_delete_contact_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_2',
            name='status',
            field=models.CharField(default='pending', max_length=400),
        ),
    ]
